apiVersion: apps/v1
kind: Deployment
metadata:
  name: multichain-node
spec:
  template:
    spec:
      containers:
      - name: multichain-node
        image: sensrnet-multichain_multichain-node:latest
        imagePullPolicy: Never
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: multichain-node-data
      volumes:
        - name: multichain-node-data
          persistentVolumeClaim:
            claimName: multichain-node-pvc
