version: '3.7'

services:

    masternode:
        build:
            context: master
            dockerfile: Dockerfile
        expose:
            - 8571
            - 8570
        ports:
            - 8571:8571
            - 8570:8570
        environment:
            CHAINNAME: MyChain
            NETWORK_PORT: 8571
            RPC_PORT: 8570
            RPC_USER: multichainrpc
            RPC_PASSWORD: password
            RPC_ALLOW_IP: 0.0.0.0/0.0.0.0
            PARAM_TARGET_BLOCK_SIZE: target-block-time|30
            PARAM_ANYONE_CAN_CONNECT: anyone-can-connect|true
            PARAM_ANYONE_CAN_MINE: anyone-can-mine|true

    node:
        build:
            context: node
            dockerfile: Dockerfile
        expose:
            - 8571
            - 8570
        ports:
            - 8573:8571
            - 8572:8570
        environment:
            CHAINNAME: MyChain
            NETWORK_PORT: 8571
            RPC_PORT: 8570
            RPC_USER: multichainrpc
            RPC_PASSWORD: password
            RPC_ALLOW_IP: 0.0.0.0/0.0.0.0
            MASTER_NODE: masternode
        links:
            - masternode
        depends_on:
            - masternode

    explorer:
        build:
            context: explorer
            dockerfile: Dockerfile
        expose:
            - 2750
            - 8571
            - 8570
        ports:
            - 2750:2750
        environment:
            CHAINNAME: MyChain
            NETWORK_PORT: 8571
            RPC_PORT: 8570
            RPC_USER: multichainrpc
            RPC_PASSWORD: password
            RPC_ALLOW_IP: 0.0.0.0/0.0.0.0
            MASTER_NODE_HOST: masternode
        links:
            - masternode
        depends_on:
            - masternode

    # multichain-node:
    #     build:
    #         context: multichain-node
    #         dockerfile: Dockerfile
    #     expose:
    #         - 8571
    #         - 8570
    #         - 2750
    #     ports:
    #         - 8571:8571
    #         - 8570:8570
    #         - 2750:2750
    #     environment:
    #         CHAINNAME: MyChain
    #         NETWORK_PORT: 8571
    #         RPC_PORT: 8570
    #         RPC_USER: multichainrpc
    #         RPC_PASSWORD: password
    #         RPC_ALLOW_IP: 0.0.0.0/0.0.0.0
    #         PARAM_TARGET_BLOCK_SIZE: target-block-time|30
    #         PARAM_ANYONE_CAN_CONNECT: anyone-can-connect|true
    #         PARAM_ANYONE_CAN_MINE: anyone-can-mine|true
