version: '3.7'

volumes:
    # Volumes need to be recreated when starting a new chain: 'docker-compose down -v'.
    main-node-data:
        driver: local

    node-data:
        driver: local

services:

    main-node:
        build:
            context: .
            dockerfile: Dockerfile
        expose:
            - 2750
            - 8570
            - 8571
        ports:
            - 2750:2750
            - 8570:8570
            - 8571:8571
        volumes:
            - main-node-data:/data
        environment:
            CHAINNAME: SensRNet
            NETWORK_PORT: 8571
            RPC_PORT: 8570
            RPC_USER: multichainrpc
            RPC_PASSWORD: password
            RPC_ALLOW_IP: 0.0.0.0/0.0.0.0
            DELAY_INIT: 0
            PARAM_TARGET_BLOCK_SIZE: target-block-time|30
            PARAM_ANYONE_CAN_CONNECT: anyone-can-connect|true
            PARAM_ANYONE_CAN_MINE: anyone-can-mine|true
            PARAM_PRIVATE_KEY_VERSION: private-key-version|809748bc
            PARAM_ADDRESS_CHECKSUM_VALUE: address-checksum-value|26ccd85d
            PARAM_ADDRESS_PUBKEYHASH_VERSION: address-pubkeyhash-version|00bb4a06

    node:
        build:
            context: .
            dockerfile: Dockerfile
        expose:
            - 2751
            - 8572
            - 8573
        ports:
            - 2751:2750
            - 8572:8570
            - 8573:8571
        volumes:
            - node-data:/data
        environment:
            CHAINNAME: SensRNet
            NETWORK_PORT: 8571
            RPC_PORT: 8570
            RPC_USER: multichainrpc
            RPC_PASSWORD: password
            RPC_ALLOW_IP: 0.0.0.0/0.0.0.0
            MAIN_NODE_HOST: main-node
            DELAY_INIT: 1
        links:
            - main-node
        depends_on:
            - main-node
