apiVersion: apps/v1
kind: Deployment
metadata:
  name: multichain-node
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: multichain-node
        image: sensrnetregistry.azurecr.io/sensrnet/multichain-node:latest
        env:
        - name: CHAINNAME
          value: MyChain
        - name: MASTER_NODE_HOST
          value: 20.54.161.4
        - name: NETWORK_PORT
          value: "7557"
        - name: RPC_ALLOW_IP
          value: 0.0.0.0/0.0.0.0
        - name: RPC_USER
          valueFrom:
              secretKeyRef:
                name: json-rpc-credentials
                key: username
        - name: RPC_PASSWORD
          valueFrom:
              secretKeyRef:
                name: json-rpc-credentials
                key: password
        - name: RPC_PORT
          value: "8570"
        ports:
        - name: rpc
          containerPort: 8570
        - name: tcp
          containerPort: 8571
        - name: web
          containerPort: 2750
        volumeMounts:
        - mountPath: /data
          name: multichain-node-data
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
