# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   name: masternode-ingress
#   annotations:
#     kubernetes.io/ingress.class: traefik
#     traefik.ingress.kubernetes.io/preserve-host: "true"
#     # traefik.ingress.kubernetes.io/request-modifier: ReplacePathRegex: ^/:7557/(.*) /$1"
# spec:
#   rules:
#   - http:
#       paths:
#       - backend:
#           serviceName: masternode
#           servicePort: 7557
