apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: explorer-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/preserve-host: "true"
    traefik.ingress.kubernetes.io/request-modifier: "ReplacePathRegex: ^/internal/explorer/(.*) /$1"
spec:
  rules:
  - host: localhost
  - http:
      paths:
      - backend:
          serviceName: explorer
          servicePort: 2750
        path: /internal/explorer
