apiVersion: v1
kind: Service
metadata:
  labels:
    app: node
  name: node
  namespace: node
spec:
  ports:
  - port: 7558
    targetPort: 7557
  - port: 8003
    targetPort: 8002
  selector:
    app: node
