apiVersion: v1
kind: Service
metadata:
  labels:
    app: node
  name: node-service
spec:
  ports:
  - name: "7557"
    port: 7557
    targetPort: 7557
  - name: "8002"
    port: 8002
    targetPort: 8002
  selector:
    app: node
