name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  DOCKERHUB_NAMESPACE: sensrnetnl
  REPOSITORY: multichain-node

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: ${{ env.DOCKERHUB_NAMESPACE }}/${{ env.REPOSITORY }}:${{ github.sha }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ env.DOCKERHUB_NAMESPACE }}/${{ env.REPOSITORY }}:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
